ProjetoMyTe.AppWeb/Controllers/CargosController.cs
using Microsoft.AspNetCore.Mvc;
using ProjetoMyTe.AppWeb.Services;

namespace ProjetoMyTe.AppWeb.Controllers
{
    public class CargosController : Controller
    {
        private readonly CargosService cargosService;
        public CargosController(CargosService cargosService)
        {
            this.cargosService = cargosService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ListarCargos()
        {
            var lista = cargosService.Listar();
            return View(lista);
        }

    }
}

ProjetoMyTe.AppWeb/Controllers/RegistroHorasController.cs
using Microsoft.AspNetCore.Mvc;
using ProjetoMyTe.AppWeb.Models.Entities;
using ProjetoMyTe.AppWeb.Services;
using System;

namespace ProjetoMyTe.AppWeb.Controllers
{

    public class RegistroHorasController : Controller
    {
        private readonly RegistroHorasService registroHorasService;
        public RegistroHorasController(RegistroHorasService registroHorasService)
        {
            this.registroHorasService = registroHorasService;  
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ListarRegistros()
        {
            var lista = registroHorasService.Listar();
            return View(lista);
        }

        public IActionResult IncluirRegistro()
        {
            return View();
        }

        [HttpPost]
        public IActionResult IncluirRegistro(RegistroHora registroHora)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View();
                }

                registroHora.DataRegistro = DateTime.Now;
                registroHorasService.Incluir(registroHora);
                return RedirectToAction("ListarRegistros");
            }
            catch (Exception)
            {

                throw;
            }
        }

        public IActionResult AlterarRegistro(int id)
        {
            try
            {
                if (id <= 0)
                {
                    throw new
                        ArgumentException($"O valor informado na URL ({id}) é inválido");
                }

                RegistroHora? registroHora = registroHorasService.Buscar(id);
                if (registroHora == null)
                {
                    throw new ArgumentException($"Nenhum objeto com este id: {id}");
                }
                return View(registroHora);
            }
            catch (Exception e)
            {
                return View("_Erro", e);
            }
        }

        [HttpPost]
        public IActionResult AlterarRegistro(RegistroHora registroHora)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View();
                }

                registroHorasService.Alterar(registroHora);
                return RedirectToAction("ListarRegistros"); // Requisição get
            }
            catch (Exception)
            {

                throw;
            }
        }

        public IActionResult RemoverRegistro(int id)
        {
            try
            {
                if (id <= 0)
                {
                    throw new
                        ArgumentException($"O valor informado na URL ({id}) é inválido");
                }

                RegistroHora? registroHora = registroHorasService.Buscar(id);
                if (registroHora == null)
                {
                    throw new ArgumentException($"Nenhum objeto com este id: {id}");
                }
                return View(registroHora);
            }
            catch (Exception e)
            {
                return View("_Erro", e);
            }
        }

        [HttpPost]
        public IActionResult RemoverRegistro(RegistroHora registroHora)
        {
            try
            {
                registroHorasService.Remover(registroHora);
                return RedirectToAction("ListarRegistros");
            }
            catch (Exception e)
            {
                return View("_Erro", e);
            }
        }
    }
}

ProjetoMyTe.AppWeb/Views/Shared/_Erro.cshtml
@model Exception

@{
    ViewData["Title"] = "_Erro";
}

<h1 class="text-danger">Ocorreu o seguinte erro</h1>

<div class="alert alert-danger">
    @Model.Message
</div>

ProjetoMyTe.AppWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjetoMyTe.AppWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjetoMyTe.AppWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sitemas MyTe</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cargos" asp-action="ListarCargos">Cargos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RegistroHoras" asp-action="ListarRegistros">Registros</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ProjetoMyTe.AppWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>